# Generated by Django 3.0.8 on 2020-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200801_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Coding', max_length=255, verbose_name='Category'),
        ),
    ]
