# Generated by Django 3.0.8 on 2020-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20200803_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the link above', max_length=255, verbose_name='Snippet'),
        ),
    ]
